# Generated by Django 6.0.3 on 2026-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsifi', models.TextField()),
                ('narxi', models.CharField(default='Bepul', max_length=50)),
            ],
        ),
    ]
